// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }
        if (!("communicationTimeout" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["communicationTimeout"] = time$0.Duration.$zero;
        }
        if (!("commandTimeout" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["commandTimeout"] = time$0.Duration.$zero;
        }
        if (!("reconnectPolicy" in $$source)) {
            /**
             * @member
             * @type {ReconnectPolicy}
             */
            this["reconnectPolicy"] = (new ReconnectPolicy());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reconnectPolicy" in $$parsedSource) {
            $$parsedSource["reconnectPolicy"] = $$createField3_0($$parsedSource["reconnectPolicy"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ConnectionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ConnectionDisconnected: "disconnected",
    ConnectionScanning: "scanning",
    ConnectionConnecting: "connecting",
    ConnectionAuthorizing: "authorizing",
    ConnectionConnected: "connected",
    ConnectionReconnecting: "reconnecting",
    ConnectionOffline: "offline",
    ConnectionError: "error",
};

export class DeviceProfileView {
    /**
     * Creates a new DeviceProfileView instance.
     * @param {Partial<DeviceProfileView>} [$$source = {}] - The source object to create the DeviceProfileView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("advertisedName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["advertisedName"] = "";
        }
        if (!("protocolVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocolVersion"] = "";
        }
        if (!("pairingState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pairingState"] = "";
        }
        if (!("lastSeenAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastSeenAt"] = null;
        }
        if (!("lastConnectedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastConnectedAt"] = null;
        }
        if (!("hasPassword" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasPassword"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceProfileView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceProfileView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceProfileView(/** @type {Partial<DeviceProfileView>} */($$parsedSource));
    }
}

export class DeviceState {
    /**
     * Creates a new DeviceState instance.
     * @param {Partial<DeviceState>} [$$source = {}] - The source object to create the DeviceState.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("connectionState" in $$source)) {
            /**
             * @member
             * @type {ConnectionState}
             */
            this["connectionState"] = ConnectionState.$zero;
        }
        if (!("currentFacet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentFacet"] = 0;
        }
        if (!("currentFacetKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["currentFacetKnown"] = false;
        }
        if (!("currentFacetUndefined" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["currentFacetUndefined"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["locked"] = false;
        }
        if (!("batteryPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["batteryPercent"] = 0;
        }
        if (!("systemStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemStatus"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceState(/** @type {Partial<DeviceState>} */($$parsedSource));
    }
}

export class DiscoveredDevice {
    /**
     * Creates a new DiscoveredDevice instance.
     * @param {Partial<DiscoveredDevice>} [$$source = {}] - The source object to create the DiscoveredDevice.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rssi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rssi"] = 0;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoveredDevice}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField4_0($$parsedSource["metadata"]);
        }
        return new DiscoveredDevice(/** @type {Partial<DiscoveredDevice>} */($$parsedSource));
    }
}

export class FacetConfigurationRequest {
    /**
     * Creates a new FacetConfigurationRequest instance.
     * @param {Partial<FacetConfigurationRequest>} [$$source = {}] - The source object to create the FacetConfigurationRequest.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("isPauseAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPauseAssignment"] = false;
        }
        if (!("pomodoroLimitSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pomodoroLimitSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetConfigurationRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacetConfigurationRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetConfigurationRequest(/** @type {Partial<FacetConfigurationRequest>} */($$parsedSource));
    }
}

export class FacetConfigurationView {
    /**
     * Creates a new FacetConfigurationView instance.
     * @param {Partial<FacetConfigurationView>} [$$source = {}] - The source object to create the FacetConfigurationView.
     */
    constructor($$source = {}) {
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("isPauseAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPauseAssignment"] = false;
        }
        if (!("pomodoroLimitSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pomodoroLimitSeconds"] = 0;
        }
        if (!("assignedOnDevice" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["assignedOnDevice"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetConfigurationView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacetConfigurationView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetConfigurationView(/** @type {Partial<FacetConfigurationView>} */($$parsedSource));
    }
}

export class ManualAction {
    /**
     * Creates a new ManualAction instance.
     * @param {Partial<ManualAction>} [$$source = {}] - The source object to create the ManualAction.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["inputs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManualAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManualAction}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField2_0($$parsedSource["inputs"]);
        }
        return new ManualAction(/** @type {Partial<ManualAction>} */($$parsedSource));
    }
}

export class PairingWorkflow {
    /**
     * Creates a new PairingWorkflow instance.
     * @param {Partial<PairingWorkflow>} [$$source = {}] - The source object to create the PairingWorkflow.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("currentStage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentStage"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("stages" in $$source)) {
            /**
             * @member
             * @type {StageResult[]}
             */
            this["stages"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ManualAction | null | undefined}
             */
            this["manualAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingWorkflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairingWorkflow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("manualAction" in $$parsedSource) {
            $$parsedSource["manualAction"] = $$createField4_0($$parsedSource["manualAction"]);
        }
        return new PairingWorkflow(/** @type {Partial<PairingWorkflow>} */($$parsedSource));
    }
}

export class ReconnectPolicy {
    /**
     * Creates a new ReconnectPolicy instance.
     * @param {Partial<ReconnectPolicy>} [$$source = {}] - The source object to create the ReconnectPolicy.
     */
    constructor($$source = {}) {
        if (!("initialRetryInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["initialRetryInterval"] = time$0.Duration.$zero;
        }
        if (!("mediumRetryInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["mediumRetryInterval"] = time$0.Duration.$zero;
        }
        if (!("longRetryInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["longRetryInterval"] = time$0.Duration.$zero;
        }
        if (!("offlineAfterDuration" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["offlineAfterDuration"] = time$0.Duration.$zero;
        }
        if (!("offlineAfterFailures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offlineAfterFailures"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconnectPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReconnectPolicy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconnectPolicy(/** @type {Partial<ReconnectPolicy>} */($$parsedSource));
    }
}

export class StageResult {
    /**
     * Creates a new StageResult instance.
     * @param {Partial<StageResult>} [$$source = {}] - The source object to create the StageResult.
     */
    constructor($$source = {}) {
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ManualAction | null | undefined}
             */
            this["manualAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StageResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manualAction" in $$parsedSource) {
            $$parsedSource["manualAction"] = $$createField3_0($$parsedSource["manualAction"]);
        }
        return new StageResult(/** @type {Partial<StageResult>} */($$parsedSource));
    }
}

export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

export class TaskSession {
    /**
     * Creates a new TaskSession instance.
     * @param {Partial<TaskSession>} [$$source = {}] - The source object to create the TaskSession.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("taskLabelSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskLabelSnapshot"] = "";
        }
        if (!("taskIconSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskIconSnapshot"] = "";
        }
        if (!("taskColorSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskColorSnapshot"] = "";
        }
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["endedAt"] = undefined;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("startEventNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startEventNumber"] = 0;
        }
        if (!("endEventNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endEventNumber"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSession}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskSession(/** @type {Partial<TaskSession>} */($$parsedSource));
    }
}

export class TaskSessionFilter {
    /**
     * Creates a new TaskSessionFilter instance.
     * @param {Partial<TaskSessionFilter>} [$$source = {}] - The source object to create the TaskSessionFilter.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["facet"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["to"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSessionFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSessionFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskSessionFilter(/** @type {Partial<TaskSessionFilter>} */($$parsedSource));
    }
}

export class UnpairingWorkflow {
    /**
     * Creates a new UnpairingWorkflow instance.
     * @param {Partial<UnpairingWorkflow>} [$$source = {}] - The source object to create the UnpairingWorkflow.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("currentStage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentStage"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("stages" in $$source)) {
            /**
             * @member
             * @type {StageResult[]}
             */
            this["stages"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ManualAction | null | undefined}
             */
            this["manualAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnpairingWorkflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnpairingWorkflow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("manualAction" in $$parsedSource) {
            $$parsedSource["manualAction"] = $$createField4_0($$parsedSource["manualAction"]);
        }
        return new UnpairingWorkflow(/** @type {Partial<UnpairingWorkflow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ReconnectPolicy.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = StageResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ManualAction.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
