// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }
        if (!("communicationTimeout" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["communicationTimeout"] = time$0.Duration.$zero;
        }
        if (!("commandTimeout" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["commandTimeout"] = time$0.Duration.$zero;
        }
        if (!("reconnectPolicy" in $$source)) {
            /**
             * @member
             * @type {ReconnectPolicy}
             */
            this["reconnectPolicy"] = (new ReconnectPolicy());
        }
        if (!("weekStartsOn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weekStartsOn"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("reconnectPolicy" in $$parsedSource) {
            $$parsedSource["reconnectPolicy"] = $$createField3_0($$parsedSource["reconnectPolicy"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ConnectionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ConnectionDisconnected: "disconnected",
    ConnectionScanning: "scanning",
    ConnectionConnecting: "connecting",
    ConnectionAuthorizing: "authorizing",
    ConnectionConnected: "connected",
    ConnectionReconnecting: "reconnecting",
    ConnectionOffline: "offline",
    ConnectionError: "error",
};

export class DetailedHistoryRequest {
    /**
     * Creates a new DetailedHistoryRequest instance.
     * @param {Partial<DetailedHistoryRequest>} [$$source = {}] - The source object to create the DetailedHistoryRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["to"] = undefined;
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DetailedHistoryRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DetailedHistoryRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DetailedHistoryRequest(/** @type {Partial<DetailedHistoryRequest>} */($$parsedSource));
    }
}

export class DeviceLEDSettings {
    /**
     * Creates a new DeviceLEDSettings instance.
     * @param {Partial<DeviceLEDSettings>} [$$source = {}] - The source object to create the DeviceLEDSettings.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("brightnessPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["brightnessPercent"] = 0;
        }
        if (!("blinkSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["blinkSeconds"] = 0;
        }
        if (!("confirmedOnDevice" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmedOnDevice"] = false;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceLEDSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceLEDSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceLEDSettings(/** @type {Partial<DeviceLEDSettings>} */($$parsedSource));
    }
}

export class DeviceProfileView {
    /**
     * Creates a new DeviceProfileView instance.
     * @param {Partial<DeviceProfileView>} [$$source = {}] - The source object to create the DeviceProfileView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("advertisedName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["advertisedName"] = "";
        }
        if (!("protocolVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocolVersion"] = "";
        }
        if (!("firmwareVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["firmwareVersion"] = "";
        }
        if (!("pairingState" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["pairingState"] = "";
        }
        if (!("lastSeenAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastSeenAt"] = null;
        }
        if (!("lastConnectedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["lastConnectedAt"] = null;
        }
        if (!("hasPassword" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasPassword"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceProfileView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceProfileView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceProfileView(/** @type {Partial<DeviceProfileView>} */($$parsedSource));
    }
}

export class DeviceState {
    /**
     * Creates a new DeviceState instance.
     * @param {Partial<DeviceState>} [$$source = {}] - The source object to create the DeviceState.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("connectionState" in $$source)) {
            /**
             * @member
             * @type {ConnectionState}
             */
            this["connectionState"] = ConnectionState.$zero;
        }
        if (!("currentFacet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["currentFacet"] = 0;
        }
        if (!("currentFacetKnown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["currentFacetKnown"] = false;
        }
        if (!("currentFacetUndefined" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["currentFacetUndefined"] = false;
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }
        if (!("locked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["locked"] = false;
        }
        if (!("batteryPercent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["batteryPercent"] = 0;
        }
        if (!("systemStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["systemStatus"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceState(/** @type {Partial<DeviceState>} */($$parsedSource));
    }
}

export class DeviceTapSettings {
    /**
     * Creates a new DeviceTapSettings instance.
     * @param {Partial<DeviceTapSettings>} [$$source = {}] - The source object to create the DeviceTapSettings.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("threshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["threshold"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("latency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency"] = 0;
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["window"] = 0;
        }
        if (!("confirmedOnDevice" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["confirmedOnDevice"] = false;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceTapSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DeviceTapSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceTapSettings(/** @type {Partial<DeviceTapSettings>} */($$parsedSource));
    }
}

export class DiscoveredDevice {
    /**
     * Creates a new DiscoveredDevice instance.
     * @param {Partial<DiscoveredDevice>} [$$source = {}] - The source object to create the DiscoveredDevice.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("rssi" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rssi"] = 0;
        }
        if (!("supported" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["supported"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiscoveredDevice instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiscoveredDevice}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField4_0($$parsedSource["metadata"]);
        }
        return new DiscoveredDevice(/** @type {Partial<DiscoveredDevice>} */($$parsedSource));
    }
}

export class FacetConfigurationRequest {
    /**
     * Creates a new FacetConfigurationRequest instance.
     * @param {Partial<FacetConfigurationRequest>} [$$source = {}] - The source object to create the FacetConfigurationRequest.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("isPauseAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPauseAssignment"] = false;
        }
        if (!("isPomodoroAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPomodoroAssignment"] = false;
        }
        if (!("pomodoroLimitSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pomodoroLimitSeconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetConfigurationRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacetConfigurationRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetConfigurationRequest(/** @type {Partial<FacetConfigurationRequest>} */($$parsedSource));
    }
}

export class FacetConfigurationView {
    /**
     * Creates a new FacetConfigurationView instance.
     * @param {Partial<FacetConfigurationView>} [$$source = {}] - The source object to create the FacetConfigurationView.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("isPauseAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPauseAssignment"] = false;
        }
        if (!("isPomodoroAssignment" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPomodoroAssignment"] = false;
        }
        if (!("pomodoroLimitSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pomodoroLimitSeconds"] = 0;
        }
        if (!("assignedOnDevice" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["assignedOnDevice"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FacetConfigurationView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FacetConfigurationView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FacetConfigurationView(/** @type {Partial<FacetConfigurationView>} */($$parsedSource));
    }
}

export class ManualAction {
    /**
     * Creates a new ManualAction instance.
     * @param {Partial<ManualAction>} [$$source = {}] - The source object to create the ManualAction.
     */
    constructor($$source = {}) {
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["inputs"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManualAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManualAction}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputs" in $$parsedSource) {
            $$parsedSource["inputs"] = $$createField2_0($$parsedSource["inputs"]);
        }
        return new ManualAction(/** @type {Partial<ManualAction>} */($$parsedSource));
    }
}

export class PairingWorkflow {
    /**
     * Creates a new PairingWorkflow instance.
     * @param {Partial<PairingWorkflow>} [$$source = {}] - The source object to create the PairingWorkflow.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("currentStage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentStage"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("stages" in $$source)) {
            /**
             * @member
             * @type {StageResult[]}
             */
            this["stages"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ManualAction | null | undefined}
             */
            this["manualAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairingWorkflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairingWorkflow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("manualAction" in $$parsedSource) {
            $$parsedSource["manualAction"] = $$createField4_0($$parsedSource["manualAction"]);
        }
        return new PairingWorkflow(/** @type {Partial<PairingWorkflow>} */($$parsedSource));
    }
}

export class ReconnectPolicy {
    /**
     * Creates a new ReconnectPolicy instance.
     * @param {Partial<ReconnectPolicy>} [$$source = {}] - The source object to create the ReconnectPolicy.
     */
    constructor($$source = {}) {
        if (!("initialRetryInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["initialRetryInterval"] = time$0.Duration.$zero;
        }
        if (!("mediumRetryInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["mediumRetryInterval"] = time$0.Duration.$zero;
        }
        if (!("longRetryInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["longRetryInterval"] = time$0.Duration.$zero;
        }
        if (!("offlineAfterDuration" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["offlineAfterDuration"] = time$0.Duration.$zero;
        }
        if (!("offlineAfterFailures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offlineAfterFailures"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReconnectPolicy instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReconnectPolicy}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReconnectPolicy(/** @type {Partial<ReconnectPolicy>} */($$parsedSource));
    }
}

export class ReportingPeriod {
    /**
     * Creates a new ReportingPeriod instance.
     * @param {Partial<ReportingPeriod>} [$$source = {}] - The source object to create the ReportingPeriod.
     */
    constructor($$source = {}) {
        if (!("preset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preset"] = "";
        }
        if (!("from" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["from"] = null;
        }
        if (!("to" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["to"] = null;
        }
        if (!("locale" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["locale"] = "";
        }
        if (!("timeZone" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timeZone"] = "";
        }
        if (!("weekStartsOn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["weekStartsOn"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReportingPeriod instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReportingPeriod}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReportingPeriod(/** @type {Partial<ReportingPeriod>} */($$parsedSource));
    }
}

export class StageResult {
    /**
     * Creates a new StageResult instance.
     * @param {Partial<StageResult>} [$$source = {}] - The source object to create the StageResult.
     */
    constructor($$source = {}) {
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ManualAction | null | undefined}
             */
            this["manualAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StageResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manualAction" in $$parsedSource) {
            $$parsedSource["manualAction"] = $$createField3_0($$parsedSource["manualAction"]);
        }
        return new StageResult(/** @type {Partial<StageResult>} */($$parsedSource));
    }
}

export class TapTuningObservation {
    /**
     * Creates a new TapTuningObservation instance.
     * @param {Partial<TapTuningObservation>} [$$source = {}] - The source object to create the TapTuningObservation.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("pause" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pause"] = false;
        }
        if (!("occurredAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["occurredAt"] = null;
        }
        if (!("settingsSnapshot" in $$source)) {
            /**
             * @member
             * @type {DeviceTapSettings}
             */
            this["settingsSnapshot"] = (new DeviceTapSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TapTuningObservation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TapTuningObservation}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settingsSnapshot" in $$parsedSource) {
            $$parsedSource["settingsSnapshot"] = $$createField4_0($$parsedSource["settingsSnapshot"]);
        }
        return new TapTuningObservation(/** @type {Partial<TapTuningObservation>} */($$parsedSource));
    }
}

export class TapTuningPreset {
    /**
     * Creates a new TapTuningPreset instance.
     * @param {Partial<TapTuningPreset>} [$$source = {}] - The source object to create the TapTuningPreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("settings" in $$source)) {
            /**
             * @member
             * @type {DeviceTapSettings}
             */
            this["settings"] = (new DeviceTapSettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TapTuningPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TapTuningPreset}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("settings" in $$parsedSource) {
            $$parsedSource["settings"] = $$createField3_0($$parsedSource["settings"]);
        }
        return new TapTuningPreset(/** @type {Partial<TapTuningPreset>} */($$parsedSource));
    }
}

export class TapTuningState {
    /**
     * Creates a new TapTuningState instance.
     * @param {Partial<TapTuningState>} [$$source = {}] - The source object to create the TapTuningState.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("originalSettings" in $$source)) {
            /**
             * @member
             * @type {DeviceTapSettings}
             */
            this["originalSettings"] = (new DeviceTapSettings());
        }
        if (!("draftSettings" in $$source)) {
            /**
             * @member
             * @type {DeviceTapSettings}
             */
            this["draftSettings"] = (new DeviceTapSettings());
        }
        if (!("appliedSettings" in $$source)) {
            /**
             * @member
             * @type {DeviceTapSettings}
             */
            this["appliedSettings"] = (new DeviceTapSettings());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TapTuningObservation | null | undefined}
             */
            this["lastObservation"] = undefined;
        }
        if (!("detectedCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["detectedCount"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TapTuningState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TapTuningState}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType6;
        const $$createField5_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("originalSettings" in $$parsedSource) {
            $$parsedSource["originalSettings"] = $$createField3_0($$parsedSource["originalSettings"]);
        }
        if ("draftSettings" in $$parsedSource) {
            $$parsedSource["draftSettings"] = $$createField4_0($$parsedSource["draftSettings"]);
        }
        if ("appliedSettings" in $$parsedSource) {
            $$parsedSource["appliedSettings"] = $$createField5_0($$parsedSource["appliedSettings"]);
        }
        if ("lastObservation" in $$parsedSource) {
            $$parsedSource["lastObservation"] = $$createField6_0($$parsedSource["lastObservation"]);
        }
        return new TapTuningState(/** @type {Partial<TapTuningState>} */($$parsedSource));
    }
}

export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

export class TaskSession {
    /**
     * Creates a new TaskSession instance.
     * @param {Partial<TaskSession>} [$$source = {}] - The source object to create the TaskSession.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("taskLabelSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskLabelSnapshot"] = "";
        }
        if (!("taskIconSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskIconSnapshot"] = "";
        }
        if (!("taskColorSnapshot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskColorSnapshot"] = "";
        }
        if (!("facet" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facet"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["endedAt"] = undefined;
        }
        if (!("durationSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationSeconds"] = 0;
        }
        if (!("pausedSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pausedSeconds"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["pauseStartedAt"] = undefined;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("startEventNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["startEventNumber"] = 0;
        }
        if (!("endEventNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["endEventNumber"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSession instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSession}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskSession(/** @type {Partial<TaskSession>} */($$parsedSource));
    }
}

export class TaskSessionFilter {
    /**
     * Creates a new TaskSessionFilter instance.
     * @param {Partial<TaskSessionFilter>} [$$source = {}] - The source object to create the TaskSessionFilter.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["facet"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["to"] = undefined;
        }
        if (!("overlap" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["overlap"] = false;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSessionFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSessionFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskSessionFilter(/** @type {Partial<TaskSessionFilter>} */($$parsedSource));
    }
}

export class TaskSessionPage {
    /**
     * Creates a new TaskSessionPage instance.
     * @param {Partial<TaskSessionPage>} [$$source = {}] - The source object to create the TaskSessionPage.
     */
    constructor($$source = {}) {
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {TaskSession[]}
             */
            this["sessions"] = [];
        }
        if (!("page" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (!("pageSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageSize"] = 0;
        }
        if (!("totalCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }
        if (!("hasNext" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasNext"] = false;
        }
        if (!("hasPrevious" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasPrevious"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSessionPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSessionPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField0_0($$parsedSource["sessions"]);
        }
        return new TaskSessionPage(/** @type {Partial<TaskSessionPage>} */($$parsedSource));
    }
}

export class TaskTimeSummary {
    /**
     * Creates a new TaskTimeSummary instance.
     * @param {Partial<TaskTimeSummary>} [$$source = {}] - The source object to create the TaskTimeSummary.
     */
    constructor($$source = {}) {
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }
        if (!("activeSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["activeSeconds"] = 0;
        }
        if (!("share" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["share"] = 0;
        }
        if (!("other" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["other"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskTimeSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskTimeSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskTimeSummary(/** @type {Partial<TaskTimeSummary>} */($$parsedSource));
    }
}

export class TimeReport {
    /**
     * Creates a new TimeReport instance.
     * @param {Partial<TimeReport>} [$$source = {}] - The source object to create the TimeReport.
     */
    constructor($$source = {}) {
        if (!("period" in $$source)) {
            /**
             * @member
             * @type {ReportingPeriod}
             */
            this["period"] = (new ReportingPeriod());
        }
        if (!("totalActiveSeconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalActiveSeconds"] = 0;
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {TaskTimeSummary[]}
             */
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimeReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType11;
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("period" in $$parsedSource) {
            $$parsedSource["period"] = $$createField0_0($$parsedSource["period"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        return new TimeReport(/** @type {Partial<TimeReport>} */($$parsedSource));
    }
}

export class TimeReportRequest {
    /**
     * Creates a new TimeReportRequest instance.
     * @param {Partial<TimeReportRequest>} [$$source = {}] - The source object to create the TimeReportRequest.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["from"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["to"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["now"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TimeReportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TimeReportRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TimeReportRequest(/** @type {Partial<TimeReportRequest>} */($$parsedSource));
    }
}

export class UnpairingWorkflow {
    /**
     * Creates a new UnpairingWorkflow instance.
     * @param {Partial<UnpairingWorkflow>} [$$source = {}] - The source object to create the UnpairingWorkflow.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("currentStage" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentStage"] = "";
        }
        if (!("completed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["completed"] = false;
        }
        if (!("stages" in $$source)) {
            /**
             * @member
             * @type {StageResult[]}
             */
            this["stages"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ManualAction | null | undefined}
             */
            this["manualAction"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnpairingWorkflow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnpairingWorkflow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField3_0($$parsedSource["stages"]);
        }
        if ("manualAction" in $$parsedSource) {
            $$parsedSource["manualAction"] = $$createField4_0($$parsedSource["manualAction"]);
        }
        return new UnpairingWorkflow(/** @type {Partial<UnpairingWorkflow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ReconnectPolicy.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = StageResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = ManualAction.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = DeviceTapSettings.createFrom;
const $$createType7 = TapTuningObservation.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = TaskSession.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ReportingPeriod.createFrom;
const $$createType12 = TaskTimeSummary.createFrom;
const $$createType13 = $Create.Array($$createType12);
