// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<void>}
 */
export function ConnectDevice(deviceID) {
    return $Call.ByID(2343439676, deviceID);
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectDevice(deviceID) {
    return $Call.ByID(2515401264, deviceID);
}

/**
 * @returns {$CancellablePromise<services$0.AppState>}
 */
export function GetAppState() {
    return $Call.ByID(4058975708).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {domain$0.TaskSessionFilter} filter
 * @returns {$CancellablePromise<domain$0.TaskSession[]>}
 */
export function ListTaskSessions(filter) {
    return $Call.ByID(3256966792, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.PairDeviceRequest} req
 * @returns {$CancellablePromise<domain$0.PairingWorkflow>}
 */
export function PairDevice(req) {
    return $Call.ByID(3175843602, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {domain$0.FacetConfigurationRequest} req
 * @returns {$CancellablePromise<domain$0.FacetConfigurationView>}
 */
export function SaveFacetAssignment(req) {
    return $Call.ByID(138397421, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {domain$0.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(config) {
    return $Call.ByID(3208594684, config);
}

/**
 * @param {$models.TapPauseSettingsRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function SaveTapPauseSettings(req) {
    return $Call.ByID(982819205, req);
}

/**
 * @param {$models.SaveTaskRequest} req
 * @returns {$CancellablePromise<domain$0.Task>}
 */
export function SaveTask(req) {
    return $Call.ByID(3180049120, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<domain$0.DiscoveredDevice[]>}
 */
export function ScanDevices() {
    return $Call.ByID(4085665344).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} deviceID
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPaused(deviceID, paused) {
    return $Call.ByID(2398694774, deviceID, paused);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3204128318);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(4184669029);
}

/**
 * @param {$models.UnpairDeviceRequest} req
 * @returns {$CancellablePromise<domain$0.UnpairingWorkflow>}
 */
export function UnpairDevice(req) {
    return $Call.ByID(2780315949, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = services$0.AppState.createFrom;
const $$createType1 = domain$0.TaskSession.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.PairingWorkflow.createFrom;
const $$createType4 = domain$0.FacetConfigurationView.createFrom;
const $$createType5 = domain$0.Task.createFrom;
const $$createType6 = domain$0.DiscoveredDevice.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = domain$0.UnpairingWorkflow.createFrom;
