// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../services/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<domain$0.TapTuningState>}
 */
export function BeginTapTuning(deviceID) {
    return $Call.ByID(3067096939, deviceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<domain$0.TapTuningState>}
 */
export function CancelTapTuning(deviceID) {
    return $Call.ByID(2692158010, deviceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} deviceID
 * @param {number} facet
 * @returns {$CancellablePromise<domain$0.FacetConfigurationView>}
 */
export function ClearFacetConfiguration(deviceID, facet) {
    return $Call.ByID(567621926, deviceID, facet).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {domain$0.DeviceTapSettings} settings
 * @returns {$CancellablePromise<domain$0.DeviceTapSettings>}
 */
export function ConfirmTapTuningSettings(settings) {
    return $Call.ByID(483725109, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<void>}
 */
export function ConnectDevice(deviceID) {
    return $Call.ByID(2343439676, deviceID);
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectDevice(deviceID) {
    return $Call.ByID(2515401264, deviceID);
}

/**
 * @returns {$CancellablePromise<services$0.AppState>}
 */
export function GetAppState() {
    return $Call.ByID(4058975708).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {domain$0.TimeReportRequest} req
 * @returns {$CancellablePromise<domain$0.TimeReport>}
 */
export function GetTimeReport(req) {
    return $Call.ByID(4294437127, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<domain$0.TapTuningPreset[]>}
 */
export function ListTapTuningPresets(deviceID) {
    return $Call.ByID(2967304252, deviceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {domain$0.DetailedHistoryRequest} req
 * @returns {$CancellablePromise<domain$0.TaskSessionPage>}
 */
export function ListTaskSessionPage(req) {
    return $Call.ByID(2345503744, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {domain$0.TaskSessionFilter} filter
 * @returns {$CancellablePromise<domain$0.TaskSession[]>}
 */
export function ListTaskSessions(filter) {
    return $Call.ByID(3256966792, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {$models.PairDeviceRequest} req
 * @returns {$CancellablePromise<domain$0.PairingWorkflow>}
 */
export function PairDevice(req) {
    return $Call.ByID(3175843602, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * @param {domain$0.DeviceTapSettings} settings
 * @returns {$CancellablePromise<domain$0.TapTuningState>}
 */
export function PreviewTapTuningSettings(settings) {
    return $Call.ByID(733206969, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} deviceID
 * @returns {$CancellablePromise<domain$0.FacetConfigurationView[]>}
 */
export function ResetFacetConfiguration(deviceID) {
    return $Call.ByID(3734872168, deviceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {$models.SaveDeviceNameRequest} req
 * @returns {$CancellablePromise<domain$0.DeviceProfileView>}
 */
export function SaveDeviceName(req) {
    return $Call.ByID(1719811836, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {domain$0.FacetConfigurationRequest} req
 * @returns {$CancellablePromise<domain$0.FacetConfigurationView>}
 */
export function SaveFacetAssignment(req) {
    return $Call.ByID(138397421, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {domain$0.DeviceLEDSettings} settings
 * @returns {$CancellablePromise<domain$0.DeviceLEDSettings>}
 */
export function SaveLEDSettings(settings) {
    return $Call.ByID(615670515, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {domain$0.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(config) {
    return $Call.ByID(3208594684, config);
}

/**
 * @param {$models.TapPauseSettingsRequest} req
 * @returns {$CancellablePromise<void>}
 */
export function SaveTapPauseSettings(req) {
    return $Call.ByID(982819205, req);
}

/**
 * @param {domain$0.DeviceTapSettings} settings
 * @returns {$CancellablePromise<domain$0.DeviceTapSettings>}
 */
export function SaveTapSettings(settings) {
    return $Call.ByID(1509613963, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {$models.SaveTaskRequest} req
 * @returns {$CancellablePromise<domain$0.Task>}
 */
export function SaveTask(req) {
    return $Call.ByID(3180049120, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @returns {$CancellablePromise<domain$0.DiscoveredDevice[]>}
 */
export function ScanDevices() {
    return $Call.ByID(4085665344).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} deviceID
 * @param {boolean} locked
 * @returns {$CancellablePromise<void>}
 */
export function SetLocked(deviceID, locked) {
    return $Call.ByID(941562546, deviceID, locked);
}

/**
 * @param {string} deviceID
 * @param {boolean} paused
 * @returns {$CancellablePromise<void>}
 */
export function SetPaused(deviceID, paused) {
    return $Call.ByID(2398694774, deviceID, paused);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(3204128318);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Startup() {
    return $Call.ByID(4184669029);
}

/**
 * @param {$models.UnpairDeviceRequest} req
 * @returns {$CancellablePromise<domain$0.UnpairingWorkflow>}
 */
export function UnpairDevice(req) {
    return $Call.ByID(2780315949, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

// Private type creation functions
const $$createType0 = domain$0.TapTuningState.createFrom;
const $$createType1 = domain$0.FacetConfigurationView.createFrom;
const $$createType2 = domain$0.DeviceTapSettings.createFrom;
const $$createType3 = services$0.AppState.createFrom;
const $$createType4 = domain$0.TimeReport.createFrom;
const $$createType5 = domain$0.TapTuningPreset.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = domain$0.TaskSessionPage.createFrom;
const $$createType8 = domain$0.TaskSession.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = domain$0.PairingWorkflow.createFrom;
const $$createType11 = $Create.Array($$createType1);
const $$createType12 = domain$0.DeviceProfileView.createFrom;
const $$createType13 = domain$0.DeviceLEDSettings.createFrom;
const $$createType14 = domain$0.Task.createFrom;
const $$createType15 = domain$0.DiscoveredDevice.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = domain$0.UnpairingWorkflow.createFrom;
