// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PairDeviceRequest {
    /**
     * Creates a new PairDeviceRequest instance.
     * @param {Partial<PairDeviceRequest>} [$$source = {}] - The source object to create the PairDeviceRequest.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("newPassword" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["newPassword"] = "";
        }
        if (!("allowOSPairing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowOSPairing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PairDeviceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PairDeviceRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PairDeviceRequest(/** @type {Partial<PairDeviceRequest>} */($$parsedSource));
    }
}

export class SaveTaskRequest {
    /**
     * Creates a new SaveTaskRequest instance.
     * @param {Partial<SaveTaskRequest>} [$$source = {}] - The source object to create the SaveTaskRequest.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("color" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveTaskRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveTaskRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SaveTaskRequest(/** @type {Partial<SaveTaskRequest>} */($$parsedSource));
    }
}

export class TapPauseSettingsRequest {
    /**
     * Creates a new TapPauseSettingsRequest instance.
     * @param {Partial<TapPauseSettingsRequest>} [$$source = {}] - The source object to create the TapPauseSettingsRequest.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("paused" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["paused"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TapPauseSettingsRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TapPauseSettingsRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TapPauseSettingsRequest(/** @type {Partial<TapPauseSettingsRequest>} */($$parsedSource));
    }
}

export class UnpairDeviceRequest {
    /**
     * Creates a new UnpairDeviceRequest instance.
     * @param {Partial<UnpairDeviceRequest>} [$$source = {}] - The source object to create the UnpairDeviceRequest.
     */
    constructor($$source = {}) {
        if (!("deviceID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["deviceID"] = "";
        }
        if (!("factoryReset" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["factoryReset"] = false;
        }
        if (!("allowOSUnpairing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["allowOSUnpairing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UnpairDeviceRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UnpairDeviceRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UnpairDeviceRequest(/** @type {Partial<UnpairDeviceRequest>} */($$parsedSource));
    }
}
