// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

export class AppState {
    /**
     * Creates a new AppState instance.
     * @param {Partial<AppState>} [$$source = {}] - The source object to create the AppState.
     */
    constructor($$source = {}) {
        if (!("config" in $$source)) {
            /**
             * @member
             * @type {domain$0.AppConfig}
             */
            this["config"] = (new domain$0.AppConfig());
        }
        if (!("devices" in $$source)) {
            /**
             * @member
             * @type {domain$0.DeviceProfileView[]}
             */
            this["devices"] = [];
        }
        if (!("states" in $$source)) {
            /**
             * @member
             * @type {domain$0.DeviceState[]}
             */
            this["states"] = [];
        }
        if (!("tasks" in $$source)) {
            /**
             * @member
             * @type {domain$0.Task[]}
             */
            this["tasks"] = [];
        }
        if (!("sessions" in $$source)) {
            /**
             * @member
             * @type {domain$0.TaskSession[]}
             */
            this["sessions"] = [];
        }
        if (!("facetConfigs" in $$source)) {
            /**
             * @member
             * @type {domain$0.FacetConfigurationView[]}
             */
            this["facetConfigs"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {domain$0.TaskSession | null | undefined}
             */
            this["currentSession"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        const $$createField5_0 = $$createType10;
        const $$createField6_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField0_0($$parsedSource["config"]);
        }
        if ("devices" in $$parsedSource) {
            $$parsedSource["devices"] = $$createField1_0($$parsedSource["devices"]);
        }
        if ("states" in $$parsedSource) {
            $$parsedSource["states"] = $$createField2_0($$parsedSource["states"]);
        }
        if ("tasks" in $$parsedSource) {
            $$parsedSource["tasks"] = $$createField3_0($$parsedSource["tasks"]);
        }
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField4_0($$parsedSource["sessions"]);
        }
        if ("facetConfigs" in $$parsedSource) {
            $$parsedSource["facetConfigs"] = $$createField5_0($$parsedSource["facetConfigs"]);
        }
        if ("currentSession" in $$parsedSource) {
            $$parsedSource["currentSession"] = $$createField6_0($$parsedSource["currentSession"]);
        }
        return new AppState(/** @type {Partial<AppState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = domain$0.AppConfig.createFrom;
const $$createType1 = domain$0.DeviceProfileView.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = domain$0.DeviceState.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = domain$0.Task.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = domain$0.TaskSession.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = domain$0.FacetConfigurationView.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $Create.Nullable($$createType7);
